export default `email,name,surname,plusOne,delete1,group,familyName,miembroUno,miembroDos,miembroTres,miembroCuatro,miembroCinco
,Guso,Blanco,,,Familia,Flor & Guso,Flor Blanco,,,,
,Guada,Blanco,,,Familia,"Guada, Nacho & Emi",Nacho Varone,Emi Varone,,,
,Fede,Manzuoli,,,Familia,Los Manzuoli,Carina,Sere,Pedro,,
,Andy,Blanco,,,Familia,Diaz Blanco,Hernan,Lucas Diaz,Angie,Marta,
,Juan,Tallo,,,Familia,Tallos,Eve,,,,
,Rosana,Lombardo,,,Familia,"Ro, More y Rosita",More,Rosita,,,
,,,,,Familia,,,,,,
,Leo,Lombardo,,,Familia,Leo y Mary,Mary,,,,
,Luli,Culatina,,,Familia,Luli y Diego,Diego,,,,
,Nora,,,,Familia,Nora y Ruben,Ruben,,,,
,Ale,Blanco,,,Familia,"Ale, Hernan, Tati & Sofi",Hernan,Tati,Sofi,,
,Sol,Manzuoli,,,Familia,Sol & Churex,Santi,,,,
,Andres,Adamoli,,,Maristas,Los Adamoli,Maria Adamoli,,,,
,Diego,Lennon,,,Maristas,Los Lennon,Asun,,,,
,Gabrila,Molina,,,Maristas,Los Molina,Molina,,,,
,Huevo,Chiatelino,,,Maristas,Huevo & Mariu,Mariu,,,,
,,,,,Maristas,Los Flaiban,,,,,
,Flor,Lopez Serror,,,Casi Familia,Florcita,,,,,
,Jorge,Gomez,,,Casi Familia,Los Gomez,Viviana,,,,
,Fer,,,,Casi Familia,"Fer, Cali, Clari & More",Cali,Clarita,More,,
,Sole,,,,Casi Familia,"Sole, Walter, Isa & Sofi",Walter,Sofi,Isa,,
,Joaco,Usher,,,San Lucas,Joaco & Cami,Cami,,,,
,Nico,Regueiro,,,San Lucas,Nico & Pame,Pame,,,,
,Fede,Gomez,,,San Lucas,Pefu & Tefi,Tefi,,,,
,Nacho,Vila,,,San Lucas,Nacho & Mechi,Mechi,,,,
,Leo,Benavidez,,,San Lucas,Leo & Agus ,Agus,,,,
,Guido,Barberia,1,,San Lucas,Dogui,,,,,
,Santi,Rizzi,,,San Lucas,Santi & Agus,Agus,,,,
,Diego,Gabrieli,,,Rolito,Diego & Male,Male,,,,
,Ignacio,,,,Rolito,Ori & Mel,Mel,,,,
,Sebastian,Bronico,,,Rolito,Seba & Vic,Vic,,,,
,Cuth,,,,Rolito,Cuth,,,,,
,Any,,1,,Amigos,Any ,,,,,
,Pala,,,,Amigos,Pala,,,,,
,Chicho,,,,Amigos,Chicho,,,,,
,Caro,,,,Amigos,Caro ,,,,,
,Juli,,,,DH,Juli & Sergio,Sergio,,,,
,Sofi,,,,DH,Sofi,,,,,
,Sol,,,,DH,Sol & Alex,Alex,,,,
,Augusto,,,,DH,Augusto,,,,,
,Tomi,,,,DH,Tomi & Pao,Pao,,,,
,Adri,,,,DH,Adri,,,,,
,Cris,,,,DH,Cris,,,,,
,Anto,,,,DH,Anto & Leo,Leo,,,,
,Ale,,,,DH,Ale ,Silvi,,,,
,Viole,,,,UX,Viole & Damian,Damian,,,,
,Dash,,,,UX,Dash & Fede,Fede,,,,
,Gi,,,,UX,Gi ,,,,,
,Fernando,Urraibaru,,,Rolito,Fer,,,,,
,Erica,,,,Casi Familia,Erica,,,,,
,Sonia,,1,,Casi Familia,Sonia,,,,,
,Ari,,,,DH,Ari & Sol,Sol,,,,
,Adrián,Maradei,,,Casi Familia,"Adrian, Silvia & Santino",Silvia,Santino,,,`

export const dirName = import.meta.url
